- name: Request the token
  become: false
  ansible.builtin.uri: 
    method: POST
    url: https://api.github.com/repos/{{ lookup('ansible.builtin.env', 'GH_REPO') }}/actions/runners/registration-token
    headers:
      Accept: application/vnd.github+json
      Authorization: Bearer {{ lookup('ansible.builtin.env', 'GH_TOKEN') }}
      X-GitHub-Api-Version: 2022-11-28
    status_code: 201
  register: response 

- name: Save token
  become: false
  shell: "echo {{ response.json.token }} > {{ token_file_path }}"
  args:
    chdir: "{{ action_dir }}"
   
- name: Register an ephemeral runner
  become: false
  shell: ./config.sh --url https://github.com/{{gh_repo}} --token $(cat ./gh_token) --ephemeral --unattended 
  args:
    chdir: "{{ action_dir }}"